# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- azure_migration_test

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  container: aloysbaillet/aswf-openvdb-vfx:latest
  steps:
  - bash: ci/build.sh clang++ Release 6 ON
    displayName: build_abi6
  - bash: ./build/openvdb/unittest/vdb_test -v
    displayName: test
